server:
  port: 8085
  servlet:
    context-path: /v1/auth-service
    
    
spring:
  application:
    name: GPJ-AUTH-SERVICE
    
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gpj_test
    username: root
    password: mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    table: auth_flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 0
    locations: db/migration
jwt:
  secret:
    key: BJmThXOyoUK8cqS+9F9xIfF0exOYjNc+BAQFJvr3UpCDu+oO6MHEpSmroIqTuUjF
maximum:
  token:
    expiration: 15
