
-- Create the USER table
CREATE TABLE USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    NAME VARCHAR(255),
    LAST_LOGGED_IN DATETIME,
    DEVICE VARCHAR(255),
    EMAIL VARCHAR(255),
    MOBILE VARCHAR(255),
    PASSWORD_EXPIRATION_DATE DATETIME
);

-- Create the PROFILE table
CREATE TABLE PROFILE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    CODE VARCHAR(255) UNIQUE,
    DESCRIPTION VARCHAR(255) NOT NULL
);

-- Create the PERMISSION table
CREATE TABLE PERMISSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    CODE VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

-- Create the USER_PROFILE table
CREATE TABLE USER_PROFILE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    PROFILE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL
);

-- Create the USER_PERMISSION table
CREATE TABLE USER_PERMISSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE TINYINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    PERMISSION_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);

-- Add foreign key constraints
ALTER TABLE USER_PROFILE
    ADD CONSTRAINT FK_USER_PROFILE_PROFILE FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (ID);

ALTER TABLE USER_PROFILE
    ADD CONSTRAINT FK_USER_PROFILE_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (ID);

ALTER TABLE USER_PERMISSION
    ADD CONSTRAINT FK_USER_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (ID);

ALTER TABLE USER_PERMISSION
    ADD CONSTRAINT FK_USER_PERMISSION_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID);

INSERT INTO PERMISSION (CODE, DESCRIPTION,ACTIVE,CREATED_AT) VALUES
    ('RUN_TESTS', 'Write Permission','1',now());



